version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "ci"]
    commit-message:
      prefix: "ci"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
    labels: ["dependencies", "kotlin"]
    commit-message:
      prefix: "deps"
    ignore:
      - dependency-name: "org.jetbrains.kotlin:*"
        update-types: ["version-update:semver-major"]
