rootProject.name = "kap"
include(":kap-core")
include(":kap-resilience")
include(":kap-arrow")
include(":benchmarks")
include(":examples:ecommerce-checkout")
include(":examples:dashboard-aggregator")
include(":examples:validated-registration")
include(":examples:ktor-integration")
include(":examples:resilient-fetcher")
include(":examples:full-stack-order")
