package kap.ksp

import com.google.devtools.ksp.processing.*
import com.google.devtools.ksp.symbol.*
import com.google.devtools.ksp.validate
import java.io.OutputStreamWriter

class KapTypeSafeProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val symbols = resolver.getSymbolsWithAnnotation("kap.KapTypeSafe")
        val unprocessed = mutableListOf<KSAnnotated>()

        symbols.forEach { symbol ->
            if (!symbol.validate()) {
                unprocessed.add(symbol)
                return@forEach
            }
            when (symbol) {
                is KSClassDeclaration -> {
                    if (symbol.classKind == ClassKind.CLASS) {
                        generateForClass(symbol)
                    } else {
                        logger.error("@KapTypeSafe can only be applied to classes or functions", symbol)
                    }
                }
                is KSFunctionDeclaration -> generateForFunction(symbol)
                else -> logger.error("@KapTypeSafe can only be applied to classes or functions", symbol)
            }
        }

        return unprocessed
    }

    private data class ParamInfo(
        val name: String,
        val qualifiedType: String,
    )

    private fun generateForClass(classDecl: KSClassDeclaration) {
        val className = classDecl.simpleName.asString()
        val packageName = classDecl.packageName.asString()
        val constructor = classDecl.primaryConstructor ?: run {
            logger.error("@KapTypeSafe requires a primary constructor", classDecl)
            return
        }

        val params = constructor.parameters.map { param ->
            ParamInfo(
                name = param.name!!.asString(),
                qualifiedType = param.type.resolve().declaration.qualifiedName?.asString()
                    ?: param.type.resolve().toString(),
            )
        }

        if (params.isEmpty()) {
            logger.error("@KapTypeSafe requires at least one parameter", classDecl)
            return
        }

        val returnType = if (packageName.isEmpty()) className else "$packageName.$className"

        generate(
            containingFile = classDecl.containingFile!!,
            packageName = packageName,
            baseName = className,
            safeFunctionName = "kapSafe",
            params = params,
            returnType = returnType,
            isSuspend = false,
        )
    }

    private fun generateForFunction(funcDecl: KSFunctionDeclaration) {
        val funcName = funcDecl.simpleName.asString()
        val packageName = funcDecl.packageName.asString()

        val params = funcDecl.parameters.map { param ->
            ParamInfo(
                name = param.name!!.asString(),
                qualifiedType = param.type.resolve().declaration.qualifiedName?.asString()
                    ?: param.type.resolve().toString(),
            )
        }

        if (params.isEmpty()) {
            logger.error("@KapTypeSafe requires at least one parameter", funcDecl)
            return
        }

        val returnTypeRef = funcDecl.returnType?.resolve()
        val returnType = returnTypeRef?.declaration?.qualifiedName?.asString()
            ?: returnTypeRef?.toString()
            ?: "kotlin.Unit"

        val isSuspend = funcDecl.modifiers.contains(Modifier.SUSPEND)
        val baseName = funcName.replaceFirstChar { it.uppercase() }

        generate(
            containingFile = funcDecl.containingFile!!,
            packageName = packageName,
            baseName = baseName,
            safeFunctionName = "kapSafe${baseName}",
            params = params,
            returnType = returnType,
            isSuspend = isSuspend,
            originalFunctionName = funcName,
        )
    }

    private fun generate(
        containingFile: KSFile,
        packageName: String,
        baseName: String,
        safeFunctionName: String,
        params: List<ParamInfo>,
        returnType: String,
        isSuspend: Boolean,
        originalFunctionName: String? = null,
    ) {
        val hasPackage = packageName.isNotEmpty()

        val file = codeGenerator.createNewFile(
            Dependencies(true, containingFile),
            packageName,
            "${baseName}KapTypeSafe"
        )

        OutputStreamWriter(file).use { writer ->
            writer.write("// AUTO-GENERATED by kap-ksp — do not edit\n")
            if (hasPackage) {
                writer.write("package $packageName\n\n")
            }
            writer.write("import kap.Kap\n")
            writer.write("import kap.of\n\n")

            // Generate value class wrappers
            val wrapperNames = params.map { param ->
                val wrapperName = "$baseName${param.name.replaceFirstChar { it.uppercase() }}"
                writer.write("@JvmInline\n")
                writer.write("value class $wrapperName(val value: ${param.qualifiedType})\n\n")
                wrapperName
            }

            // Build types
            val originalTypes = params.joinToString(", ") { it.qualifiedType }
            val suspendPrefix = if (isSuspend) "suspend " else ""
            val curriedType = wrapperNames.joinToString(" -> ") { "($it)" } + " -> $returnType"

            // Doc comment
            val target = originalFunctionName ?: baseName
            writer.write("/**\n")
            writer.write(" * Type-safe variant of `kap(::$target)` where each parameter\n")
            writer.write(" * has a distinct wrapper type — swapping same-typed parameters\n")
            writer.write(" * causes a compile error.\n")
            writer.write(" */\n")

            // Function signature
            writer.write("fun $safeFunctionName(f: $suspendPrefix($originalTypes) -> $returnType): Kap<$curriedType> =\n")
            writer.write("    Kap.of(")

            // Build nested lambda
            val paramNames = params.indices.map { "p$it" }
            paramNames.zip(wrapperNames).forEach { (name, wrapper) ->
                writer.write("{ $name: $wrapper -> ")
            }
            val callArgs = paramNames.joinToString(", ") { "$it.value" }
            writer.write("f($callArgs)")
            writer.write(" }".repeat(params.size))
            writer.write(")\n")
        }
    }
}
